Category to tag
kookmin-sw/capstone-2020-12 pull request #173
Opened 2020-10-21 10:10 UTC by gee05053

#159 
1. tag 테이블 생성 → tag id와 tag name 정의
2. tag_media_connect 테이블 생성 → tag id와 연결된 media id 정의
3. resolver 구현
 - 스키마 수정
 - category를 지움으로써 query 수정
 - mutation 변경(uploadMedia 말고는 deleteMedia, modifyMedia 동작 확인)

2020-10-22 06:11 UTC, Lhyejin approved these changes

2020-10-22 06:21 UTC, Sujin-Kim1 approved these changes

2020-10-25 06:55 UTC, yun-kwak requested changes
수고하셨네요 🤣 
리뷰 조금 남겨놨습니다. 확인해보시고 이해안되는게 있으면 전화주시죠

2020-10-25 06:55 UTC, yun-kwak commented on src/server/data-sources.js
> +      .join("tag_media_connect", "tag_media_connect.mediaId", "media.id")
이렇게 하면 항상 미디어 테이블의 모든 레코드와 tag_media_connect를 항상 조인하게 돼서 미디어의 갯수가 늘어날 수록 매우 느려질 수 있습니다.
사실 뭐 검색 기능을 잘 만드려면 elasticsearch처럼 inverted index같은 걸 하는게 좋지만,,, 이걸 하기엔 시간이 없으니 그냥 알아두시면 좋을 듯 싶습니다.

2020-10-25 06:55 UTC, yun-kwak commented on src/server/data-sources.js
> +class TagDB extends SQLDataSource {
Tag와 TagMediaConnectDB를 따로 빼기엔 너무 자잘한 것 같습니다. 어차피 Media가 포함하는 하위 개념이기 때문에 MediaDB에 통합하는 편이 좋을 것 같습니다.

2020-10-25 06:55 UTC, yun-kwak commented on src/server/schema.js
> +    tag_name: String!
camelCase를 지켜주세요

2020-10-25 06:55 UTC, yun-kwak commented on src/server/resolvers/mutation.js
> +    tag_names.forEach(async function(tag_name){
camelCase를 지켜주세요. 언급하지 않은 다른 부분도 마찬가지입니다.

2020-10-25 06:55 UTC, yun-kwak commented on src/server/data-sources.js
> +  async getTagNameByMediaId(id) {
이름은 getTagName인데 실제로 반환하는 것은 id, mediaId, tagName입니다.

2020-10-25 06:55 UTC, yun-kwak commented on src/server/data-sources.js
> +    if(tagId.length == 0) { //등록된 tag가 아니라면 tag먼저 추가하기
falsy한 값은 굳이 명시하지 않고 if (!tagId)로 가는게 더 가독성이 좋을 것 같습니다.

2020-10-25 06:55 UTC, yun-kwak commented on src/server/data-sources.js
> +      tagId = await this.knex("tag").select("id").where({ tag_name: tag_name }); //리스트안에 사전 형태로 들어옴. -> [ {id: 0} ]
여기선 insert한 뒤에 다시 조회해서 받아오고 있는 데,  insert하면서 한번에 받아오는게 더 빠를 것 같습니다.
제가 작성한 addMedia등을 참고하세요

2020-10-25 06:55 UTC, yun-kwak commented on src/server/resolvers/mutation.js
> +      await tagMediaConnectDB.addTagMediaConnect(tag_name, id);
이렇게 connect를 delete하는 연산과 forEach로 tag_names를 순환하며 tag media connect를 추가하는 연산을 따로 진행하면 
해당 작업들이 진행되는 사이, 이 미디어를 조회하려하면 만들다만 tag정보를 반환받게 될 수 있습니다.
eg.) media tag connect모두 delete되고 새로운 connect는 하나만 추가되었는데, 그 사이 다른 사용자가 해당 미디어 조회를 요청 해당 미디어의 tag정보에는 하나 보이게됨.
트랜잭션에 대해 찾아보세요.

2020-10-25 06:55 UTC, yun-kwak commented on src/server/resolvers/mutation.js
> +    tag_names.forEach(async function(tag_name){ //tag_names는 리스트로 올 것임.
이 작업도 밑에서 언급한 transaction 문제와 마찬가지 입니다. tag는 심각하게 중요한 정보는 아니라서 크게 상관없을 순 있지만 좋지 못한 경험을 만들어낼 수 있습니다.
그리고 이와 별개로 이런 식으로 DB에 여러번 접근하는 일이 필요하다면 resolver에서 처리하기 보단 DataSource단에 method를 따로 만드는게 좋을 것 같습니다.

2020-10-25 06:55 UTC, yun-kwak commented on src/server/migrations/20201015222316_change_category_to_tag.js
> +  let mediaJoinResult = await knex("media").join("tag", "tag.tag_name", "media.category").select("tag.id as tag", "media.id as media");
어차피 migration은 거의 1회성 코드긴 하지만 tag.id와 media.id를 그냥 tag와 media로 alias를 지정하는 건 개인적으로 조금은 안좋은 naming이라고 생각됩니다.

2020-10-25 06:55 UTC, yun-kwak commented on src/server/migrations/20201015222316_change_category_to_tag.js
> +  await knex.schema.createTable("tag_media_connect", function(table) {
primary어디갔죠???

2020-10-25 06:55 UTC, yun-kwak commented on src/server/migrations/20201015222316_change_category_to_tag.js
> +  mediaJoinTagName.forEach(async function(row) {
태그가 있는 모든 레코드를 삭제하고 모든 필드를 다시 쓰는 것 보단 category 필드만 업데이트하면 될 것 같습니다. (속도면에서 차이가 날 것 같습니다.)

2020-10-25 06:55 UTC, yun-kwak commented on src/server/data-sources.js
> +  async getTagNameByMediaId(id) {
그리고 GraphQL에서는 굳이 join을 사용하지 않아도 되는 경우가 많습니다. 사용자가 굳이 필요로 하지 않을 수 있는 정보를 데이터베이스로부터 미리 가져올 필요가 없기 때문이죠. 사용자가 필요로 할 때(GraphQL 쿼리에서 명시했을 때)만 db로부터 가져오면 됩니다.

(TMI, 아마 DB의 최적화 덕분에 추가적인 정보(지금의 tag같은)가 필요한 경우 DB에 세번 따로 요청하는 것보단(media 테이블에 한번, tag_media_connect에한번, tag에 한번) join으로 미리 한번에 가져오는게 빠르다 생각할 수도 있지만 캐싱을 해놓으면 생각보다 속도도 차이 안나고 필요할 때만 가져오는게 코드도 간단해지고 이렇게 안짜면 중복으로 데이터를 가져오는 비효율적인 경우가 생깁니다.)

2020-10-28 00:50 UTC, Sujin-Kim1 approved these changes

2020-10-28 00:50 UTC, Sujin-Kim1 commented on src/server/migrations/20201009173516_rename_body_to_content.js
> +  await knex.schema.table("comment", function (table) {
이거 master에서 바로 올렸었는디??? 그 때 올리라고 해가지구 ㅠ.ㅠ

2020-10-28 01:59 UTC, gee05053 commented
나 저거 push한적 없는데;; 리베이스하면서 잘못올라갔나봐;

2020년 10월 28일 (수) 09:50, Sujin Kim <notifications@github.com>님이 작성:

> *@Sujin-Kim1* approved this pull request.
> ------------------------------
>
> In src/server/migrations/20201009173516_rename_body_to_content.js
> <https://github.com/kookmin-sw/capstone-2020-12/pull/173#discussion_r513108934>
> :
>
> > @@ -1,11 +1,11 @@
>
>  exports.up = async function (knex) {
>
> -  knex.schema.table("comment", function (table) {
>
> +  await knex.schema.table("comment", function (table) {
>
>
> 이거 master에서 바로 올렸었는디??? 그 때 올리라고 해가지구 ㅠ.ㅠ
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kookmin-sw/capstone-2020-12/pull/173#pullrequestreview-518243424>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG2CSHIS64CVGVBGCBXZIYLSM5TGHANCNFSM4SZR2TXQ>
> .
>

2020-10-28 09:51 UTC, gee05053 commented on src/server/migrations/20201009173516_rename_body_to_content.js
> +  await knex.schema.table("comment", function (table) {
제가 리베이스하면서 실수인거 같습니다... 죄송합니다

2020-10-28 11:59 UTC, yun-kwak commented on src/server/data-sources.js
> +    return await this.knex
return으로 대체 가능합니다

2020-10-28 12:13 UTC, yun-kwak approved these changes
Please change the codes I mentioned in person.

2020-10-29 12:41 UTC, merged